json.id item.id
json.user_id item.user_id
json.name item.name
json.description item.description
json.size item.size
json.image item.image
json.condition item.condition
json.retail_price item.retail_price
json.selling_price item.selling_price
json.user item.user
